name: Test workflow
inputs:
  status:
    description: 'The status to announce'
    required: true
    type: string

jobs:
  announce:
    name: Announce
    runs-on: ubuntu-latest
    steps:
      - run: echo "Status is ${{ inputs.status}}"
      
